// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SagaBank.Debits;

#nullable disable

namespace SagaBank.Debits.Migrations
{
    [DbContext(typeof(DebitContext))]
    [Migration("20230413172722_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("SagaBank.Debits.Debit", b =>
                {
                    b.Property<byte[]>("TransactionId")
                        .HasColumnType("BLOB");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("DebitAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId");

                    b.ToTable("Debits");
                });
#pragma warning restore 612, 618
        }
    }
}
