# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: sagabank
services:
- name: sagabank-backend
  project: src/SagaBank.Backend/SagaBank.Backend.csproj
- name: sagabank-frontend
  project: src/SagaBank.Frontend/SagaBank.Frontend.csproj
- name: sagabank-transactions
  project: src/SagaBank.Transactions/SagaBank.Transactions.csproj
  replicas: 6
#- name: sagabank-credits
#  project: src/SagaBank.Credits/SagaBank.Credits.csproj

- name: sagabank-kafka-zookeeper
  image: confluentinc/cp-zookeeper:7.3.2
  env:
  - ZOOKEEPER_CLIENT_PORT=2181
  - ZOOKEEPER_TICK_TIME=2000

- name: sagabank-kafka-broker
  image: confluentinc/cp-kafka:7.3.2
  bindings:
  - port: 9092
  env:
  - KAFKA_BROKER_ID=1
  - KAFKA_ZOOKEEPER_CONNECT="sagabank-kafka-zookeeper:2181"
  - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP="PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT"
  - KAFKA_ADVERTISED_LISTENERS="PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://sagabank-kafka-broker:29092"
  - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
  - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
  - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1

- name: sagabank-kafka-ui
  image: provectuslabs/kafka-ui:latest
  bindings:
  - port: 9091
    containerPort: 8080
    protocol: http
  env:
  - KAFKA_CLUSTERS_0_NAME="local"
  - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS="sagabank-kafka-broker:29092"
  - DYNAMIC_CONFIG_ENABLED="true"

# - name: sagabank-kafka-schema-registry
#   image: confluentinc/cp-schema-registry:7.3.3
#   bindings:
#   - port: 8081
#     protocol: http
#   env:
#   - SCHEMA_REGISTRY_HOST_NAME="sagabank-kafka-schema-registry"
#   - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS="sagabank-kafka-broker:29092"
#   - SCHEMA_REGISTRY_LISTENERS="http://0.0.0.0:8081"


# - name: sagabank-kafka-controlcenter
#   image: confluentinc/cp-enterprise-control-center:7.3.3
#   bindings:
#   - port: 9021
#     protocol: http
#   env:
#  - CONTROL_CENTER_BOOTSTRAP_SERVERS="sagabank-kafka-broker:29092"
#  - CONTROL_CENTER_CONNECT_CONNECT-DEFAULT_CLUSTER='connect:8083'
#  - CONTROL_CENTER_KSQL_KSQLDB1_URL="http://ksqldb-server:8088"
#  - CONTROL_CENTER_KSQL_KSQLDB1_ADVERTISED_URL="http://localhost:8088"
#  - CONTROL_CENTER_SCHEMA_REGISTRY_URL="http://sagabank-kafka-schema-registry:8081"
#  - CONTROL_CENTER_REPLICATION_FACTOR=1
#  - CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS=1
#  - CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS=1
#  - CONFLUENT_METRICS_TOPIC_REPLICATION=1
#  - PORT=9021